// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "O_CHARSET_NAME$subexpression$1$string$1", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":"5"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$1"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$2"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$3"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$4", "symbols": [{"literal":"h"}, {"literal":"p"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$4"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$5", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$5"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$6", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$6"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$7", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$7"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$8", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"7"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$8"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$9", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$9"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$10", "symbols": [{"literal":"u"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$10"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$11", "symbols": [{"literal":"s"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$11"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$12", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$12"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$13", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"s"}, {"literal":"6"}, {"literal":"2"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$13"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$14", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$14"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$15", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$15"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$16", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"2"}, {"literal":"3"}, {"literal":"1"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$16"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$17", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$17"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$18", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$18"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$19", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$19"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$20", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"5"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$20"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$21", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$21"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$22", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$22"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$23", "symbols": [{"literal":"u"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$23"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$24", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"6"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$24"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$25", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"b"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$25"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$26", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$26"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$27", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$27"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$28", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$28"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$29", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"7"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$29"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$30", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}, {"literal":"m"}, {"literal":"b"}, {"literal":"4"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$30"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$31", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$31"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$32", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$32"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$33", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$33"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$34", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$34"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$35", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"7"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$35"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$36", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"3"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$36"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$37", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$37"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$38", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":"d"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$38"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$39", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"9"}, {"literal":"3"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$39"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$40", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"j"}, {"literal":"p"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$40"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$41", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"1"}, {"literal":"8"}, {"literal":"0"}, {"literal":"3"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$41"]},
    {"name": "O_CHARSET_NAME", "symbols": ["O_CHARSET_NAME$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "O_COLLATION_NAME$subexpression$1$string$1", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":"5"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$1"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"8"}, {"literal":"_"}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$2"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"0"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$3"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$4", "symbols": [{"literal":"h"}, {"literal":"p"}, {"literal":"8"}, {"literal":"_"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$4"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$5", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"r"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$5"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$6", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"1"}, {"literal":"_"}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$6"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$7", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$7"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$8", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"7"}, {"literal":"_"}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$8"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$9", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$9"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$10", "symbols": [{"literal":"u"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$10"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$11", "symbols": [{"literal":"s"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$11"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$12", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"w"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$12"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$13", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"s"}, {"literal":"6"}, {"literal":"2"}, {"literal":"0"}, {"literal":"_"}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$13"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$14", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"r"}, {"literal":"_"}, {"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$14"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$15", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"u"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$15"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$16", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"2"}, {"literal":"3"}, {"literal":"1"}, {"literal":"2"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$16"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$17", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$17"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$18", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"0"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$18"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$19", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"k"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$19"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$20", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"5"}, {"literal":"_"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"k"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$20"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$21", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}, {"literal":"8"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$21"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$22", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$22"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$23", "symbols": [{"literal":"u"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$23"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$24", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"6"}, {"literal":"6"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$24"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$25", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"b"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$25"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$26", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"e"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$26"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$27", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$27"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$28", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$28"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$29", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"7"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$29"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$30", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}, {"literal":"m"}, {"literal":"b"}, {"literal":"4"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$30"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$31", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"1"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$31"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$32", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$32"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$33", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}, {"literal":"l"}, {"literal":"e"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$33"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$34", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"6"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$34"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$35", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"7"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$35"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$36", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"3"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$36"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$37", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$37"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$38", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":"d"}, {"literal":"8"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$38"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$39", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"9"}, {"literal":"3"}, {"literal":"2"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$39"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$40", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"j"}, {"literal":"p"}, {"literal":"m"}, {"literal":"s"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$40"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$41", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"1"}, {"literal":"8"}, {"literal":"0"}, {"literal":"3"}, {"literal":"0"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$41"]},
    {"name": "O_COLLATION_NAME", "symbols": ["O_COLLATION_NAME$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "T_DEFAULT$subexpression$1", "symbols": [/[dD]/, /[eE]/, /[fF]/, /[aA]/, /[uU]/, /[lL]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DEFAULT", "symbols": ["T_DEFAULT$subexpression$1"], "postprocess": id},
    {"name": "T_RENAME$subexpression$1", "symbols": [/[rR]/, /[eE]/, /[nN]/, /[aA]/, /[mM]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_RENAME", "symbols": ["T_RENAME$subexpression$1"], "postprocess": id},
    {"name": "T_CREATE$subexpression$1", "symbols": [/[cC]/, /[rR]/, /[eE]/, /[aA]/, /[tT]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_CREATE", "symbols": ["T_CREATE$subexpression$1"], "postprocess": id},
    {"name": "T_ALTER$subexpression$1", "symbols": [/[aA]/, /[lL]/, /[tT]/, /[eE]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_ALTER", "symbols": ["T_ALTER$subexpression$1"], "postprocess": id},
    {"name": "T_DROP$subexpression$1", "symbols": [/[dD]/, /[rR]/, /[oO]/, /[pP]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DROP", "symbols": ["T_DROP$subexpression$1"], "postprocess": id},
    {"name": "T_DATABASE$subexpression$1$subexpression$1", "symbols": [/[dD]/, /[aA]/, /[tT]/, /[aA]/, /[bB]/, /[aA]/, /[sS]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DATABASE$subexpression$1", "symbols": ["T_DATABASE$subexpression$1$subexpression$1"]},
    {"name": "T_DATABASE$subexpression$1$subexpression$2", "symbols": [/[sS]/, /[cC]/, /[hH]/, /[eE]/, /[mM]/, /[aA]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DATABASE$subexpression$1", "symbols": ["T_DATABASE$subexpression$1$subexpression$2"]},
    {"name": "T_DATABASE", "symbols": ["T_DATABASE$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "T_IFEXISTS$subexpression$1", "symbols": [/[iI]/, /[fF]/, {"literal":" "}, /[eE]/, /[xX]/, /[iI]/, /[sS]/, /[tT]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_IFEXISTS", "symbols": ["T_IFEXISTS$subexpression$1"], "postprocess": id},
    {"name": "T_IFNOTEXISTS$subexpression$1", "symbols": [/[iI]/, /[fF]/, {"literal":" "}, /[nN]/, /[oO]/, /[tT]/, {"literal":" "}, /[eE]/, /[xX]/, /[iI]/, /[sS]/, /[tT]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_IFNOTEXISTS", "symbols": ["T_IFNOTEXISTS$subexpression$1"], "postprocess": id},
    {"name": "O_IFEXISTS$subexpression$1", "symbols": ["T_IFEXISTS"]},
    {"name": "O_IFEXISTS$subexpression$1", "symbols": ["T_IFNOTEXISTS"]},
    {"name": "O_IFEXISTS", "symbols": ["O_IFEXISTS$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "S_WS", "symbols": [/[ \t\n\v\f\r]/], "postprocess": id},
    {"name": "S_EOS", "symbols": [/[ \t\n\v\f\r;]/], "postprocess": id},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "S_WS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": (d) => () => null},
    {"name": "__$ebnf$1", "symbols": ["S_WS"]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", "S_WS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": (d) => () => null},
    {"name": "EOS$ebnf$1", "symbols": ["S_EOS"]},
    {"name": "EOS$ebnf$1", "symbols": ["EOS$ebnf$1", "S_EOS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "EOS", "symbols": ["EOS$ebnf$1"], "postprocess": (d) => () => null},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$1", "symbols": [/[0-9,a-z,A-Z$_]/]},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$1", "symbols": ["S_IDENTIFIER$subexpression$1$ebnf$1", /[0-9,a-z,A-Z$_]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "S_IDENTIFIER$subexpression$1", "symbols": ["S_IDENTIFIER$subexpression$1$ebnf$1"], "postprocess": d => d[0].join('')},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$2", "symbols": [/[a-zA-Z0-9_$\x01-\x59\x61-\xff]/]},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$2", "symbols": ["S_IDENTIFIER$subexpression$1$ebnf$2", /[a-zA-Z0-9_$\x01-\x59\x61-\xff]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "S_IDENTIFIER$subexpression$1", "symbols": [{"literal":"`"}, "S_IDENTIFIER$subexpression$1$ebnf$2", {"literal":"`"}], "postprocess": d => d[1].join('')},
    {"name": "S_IDENTIFIER", "symbols": ["S_IDENTIFIER$subexpression$1"], "postprocess": id},
    {"name": "main$ebnf$1", "symbols": []},
    {"name": "main$ebnf$1", "symbols": ["main$ebnf$1", "P_DDS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "main", "symbols": ["main$ebnf$1"], "postprocess": id},
    {"name": "P_DDS", "symbols": ["P_CREATE_DB"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$1$subexpression$1", "symbols": ["__", "O_IFEXISTS"]},
    {"name": "P_CREATE_DB$ebnf$1", "symbols": ["P_CREATE_DB$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB$ebnf$2$subexpression$1", "symbols": ["__", "P_CREATE_DB_SPEC"]},
    {"name": "P_CREATE_DB$ebnf$2", "symbols": ["P_CREATE_DB$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB$ebnf$3", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB", "symbols": ["_", "T_CREATE", "__", "T_DATABASE", "P_CREATE_DB$ebnf$1", "__", "S_IDENTIFIER", "P_CREATE_DB$ebnf$2", "P_CREATE_DB$ebnf$3"], "postprocess":  d => {
          return {
            database: d[6]
          }
        }},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$1$subexpression$1", "symbols": ["T_DEFAULT", "__"]},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$1", "symbols": ["P_CREATE_DB_SPEC$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"A"}, {"literal":"R"}, {"literal":"A"}, {"literal":"C"}, {"literal":"T"}, {"literal":"E"}, {"literal":"R"}, {"literal":" "}, {"literal":"S"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$2", "symbols": [{"literal":"="}], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1", "symbols": ["_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$1", "P_CREATE_DB_SPEC$subexpression$1$string$1", "_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$2", "_", "O_CHARSET_NAME", "_"], "postprocess": d => null},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$3$subexpression$1", "symbols": ["T_DEFAULT", "__"]},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$3", "symbols": ["P_CREATE_DB_SPEC$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$string$2", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"L"}, {"literal":"L"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$4", "symbols": [{"literal":"="}], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1", "symbols": ["_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$3", "P_CREATE_DB_SPEC$subexpression$1$string$2", "_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$4", "_", "O_COLLATION_NAME", "_"], "postprocess": d => null},
    {"name": "P_CREATE_DB_SPEC", "symbols": ["P_CREATE_DB_SPEC$subexpression$1"], "postprocess": d => null}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
