// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "O_CHARSET_NAME$subexpression$1$string$1", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":"5"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$1"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$2"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$3"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$4", "symbols": [{"literal":"h"}, {"literal":"p"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$4"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$5", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$5"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$6", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$6"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$7", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$7"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$8", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"7"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$8"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$9", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$9"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$10", "symbols": [{"literal":"u"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$10"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$11", "symbols": [{"literal":"s"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$11"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$12", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$12"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$13", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"s"}, {"literal":"6"}, {"literal":"2"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$13"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$14", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$14"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$15", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$15"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$16", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"2"}, {"literal":"3"}, {"literal":"1"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$16"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$17", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$17"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$18", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$18"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$19", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$19"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$20", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"5"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$20"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$21", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$21"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$22", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$22"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$23", "symbols": [{"literal":"u"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$23"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$24", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"6"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$24"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$25", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"b"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$25"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$26", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$26"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$27", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$27"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$28", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$28"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$29", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"7"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$29"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$30", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}, {"literal":"m"}, {"literal":"b"}, {"literal":"4"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$30"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$31", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$31"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$32", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$32"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$33", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$33"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$34", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$34"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$35", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"7"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$35"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$36", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"3"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$36"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$37", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$37"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$38", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":"d"}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$38"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$39", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"9"}, {"literal":"3"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$39"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$40", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"j"}, {"literal":"p"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$40"]},
    {"name": "O_CHARSET_NAME$subexpression$1$string$41", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"1"}, {"literal":"8"}, {"literal":"0"}, {"literal":"3"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_CHARSET_NAME$subexpression$1", "symbols": ["O_CHARSET_NAME$subexpression$1$string$41"]},
    {"name": "O_CHARSET_NAME", "symbols": ["O_CHARSET_NAME$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "O_COLLATION_NAME$subexpression$1$string$1", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":"5"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$1"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"8"}, {"literal":"_"}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$2"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$3", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"0"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$3"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$4", "symbols": [{"literal":"h"}, {"literal":"p"}, {"literal":"8"}, {"literal":"_"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$4"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$5", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"r"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$5"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$6", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"1"}, {"literal":"_"}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$6"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$7", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$7"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$8", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"7"}, {"literal":"_"}, {"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$8"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$9", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$9"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$10", "symbols": [{"literal":"u"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$10"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$11", "symbols": [{"literal":"s"}, {"literal":"j"}, {"literal":"i"}, {"literal":"s"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$11"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$12", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"w"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$12"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$13", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"s"}, {"literal":"6"}, {"literal":"2"}, {"literal":"0"}, {"literal":"_"}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$13"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$14", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"r"}, {"literal":"_"}, {"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$14"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$15", "symbols": [{"literal":"k"}, {"literal":"o"}, {"literal":"i"}, {"literal":"8"}, {"literal":"u"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$15"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$16", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"2"}, {"literal":"3"}, {"literal":"1"}, {"literal":"2"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$16"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$17", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$17"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$18", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"0"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$18"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$19", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"k"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$19"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$20", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"5"}, {"literal":"_"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"k"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$20"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$21", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"i"}, {"literal":"8"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$21"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$22", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$22"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$23", "symbols": [{"literal":"u"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$23"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$24", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"6"}, {"literal":"6"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$24"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$25", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"b"}, {"literal":"c"}, {"literal":"s"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$25"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$26", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"e"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$26"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$27", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$27"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$28", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"8"}, {"literal":"5"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$28"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$29", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"7"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$29"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$30", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"8"}, {"literal":"m"}, {"literal":"b"}, {"literal":"4"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$30"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$31", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"1"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$31"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$32", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$32"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$33", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"1"}, {"literal":"6"}, {"literal":"l"}, {"literal":"e"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$33"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$34", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"6"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$34"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$35", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"1"}, {"literal":"2"}, {"literal":"5"}, {"literal":"7"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$35"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$36", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"f"}, {"literal":"3"}, {"literal":"2"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$36"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$37", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$37"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$38", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":"d"}, {"literal":"8"}, {"literal":"_"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$38"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$39", "symbols": [{"literal":"c"}, {"literal":"p"}, {"literal":"9"}, {"literal":"3"}, {"literal":"2"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$39"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$40", "symbols": [{"literal":"e"}, {"literal":"u"}, {"literal":"c"}, {"literal":"j"}, {"literal":"p"}, {"literal":"m"}, {"literal":"s"}, {"literal":"_"}, {"literal":"j"}, {"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$40"]},
    {"name": "O_COLLATION_NAME$subexpression$1$string$41", "symbols": [{"literal":"g"}, {"literal":"b"}, {"literal":"1"}, {"literal":"8"}, {"literal":"0"}, {"literal":"3"}, {"literal":"0"}, {"literal":"_"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"_"}, {"literal":"c"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "O_COLLATION_NAME$subexpression$1", "symbols": ["O_COLLATION_NAME$subexpression$1$string$41"]},
    {"name": "O_COLLATION_NAME", "symbols": ["O_COLLATION_NAME$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "T_DEFAULT$subexpression$1", "symbols": [/[dD]/, /[eE]/, /[fF]/, /[aA]/, /[uU]/, /[lL]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DEFAULT", "symbols": ["T_DEFAULT$subexpression$1"], "postprocess": id},
    {"name": "T_TEMPORARY$subexpression$1", "symbols": [/[tT]/, /[eE]/, /[mM]/, /[pP]/, /[oO]/, /[rR]/, /[aA]/, /[rR]/, /[yY]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TEMPORARY", "symbols": ["T_TEMPORARY$subexpression$1"], "postprocess": id},
    {"name": "T_RENAME$subexpression$1", "symbols": [/[rR]/, /[eE]/, /[nN]/, /[aA]/, /[mM]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_RENAME", "symbols": ["T_RENAME$subexpression$1"], "postprocess": id},
    {"name": "T_CREATE$subexpression$1", "symbols": [/[cC]/, /[rR]/, /[eE]/, /[aA]/, /[tT]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_CREATE", "symbols": ["T_CREATE$subexpression$1"], "postprocess": id},
    {"name": "T_ALTER$subexpression$1", "symbols": [/[aA]/, /[lL]/, /[tT]/, /[eE]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_ALTER", "symbols": ["T_ALTER$subexpression$1"], "postprocess": id},
    {"name": "T_DROP$subexpression$1", "symbols": [/[dD]/, /[rR]/, /[oO]/, /[pP]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DROP", "symbols": ["T_DROP$subexpression$1"], "postprocess": id},
    {"name": "T_TABLE$subexpression$1", "symbols": [/[tT]/, /[aA]/, /[bB]/, /[lL]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TABLE", "symbols": ["T_TABLE$subexpression$1"], "postprocess": id},
    {"name": "T_DATABASE$subexpression$1$subexpression$1", "symbols": [/[dD]/, /[aA]/, /[tT]/, /[aA]/, /[bB]/, /[aA]/, /[sS]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DATABASE$subexpression$1", "symbols": ["T_DATABASE$subexpression$1$subexpression$1"]},
    {"name": "T_DATABASE$subexpression$1$subexpression$2", "symbols": [/[sS]/, /[cC]/, /[hH]/, /[eE]/, /[mM]/, /[aA]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DATABASE$subexpression$1", "symbols": ["T_DATABASE$subexpression$1$subexpression$2"]},
    {"name": "T_DATABASE", "symbols": ["T_DATABASE$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "T_IFEXISTS$subexpression$1", "symbols": [/[iI]/, /[fF]/, {"literal":" "}, /[eE]/, /[xX]/, /[iI]/, /[sS]/, /[tT]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_IFEXISTS", "symbols": ["T_IFEXISTS$subexpression$1"], "postprocess": id},
    {"name": "T_IFNOTEXISTS$subexpression$1", "symbols": [/[iI]/, /[fF]/, {"literal":" "}, /[nN]/, /[oO]/, /[tT]/, {"literal":" "}, /[eE]/, /[xX]/, /[iI]/, /[sS]/, /[tT]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_IFNOTEXISTS", "symbols": ["T_IFNOTEXISTS$subexpression$1"], "postprocess": id},
    {"name": "O_IFEXISTS$subexpression$1", "symbols": ["T_IFEXISTS"]},
    {"name": "O_IFEXISTS$subexpression$1", "symbols": ["T_IFNOTEXISTS"]},
    {"name": "O_IFEXISTS", "symbols": ["O_IFEXISTS$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "S_WS", "symbols": [/[ \t\n\v\f\r]/], "postprocess": id},
    {"name": "S_EOS", "symbols": [/[ \t\n\v\f\r;]/], "postprocess": id},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "S_WS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": (d) => () => null},
    {"name": "__$ebnf$1", "symbols": ["S_WS"]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", "S_WS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": (d) => () => null},
    {"name": "EOS$ebnf$1", "symbols": ["S_EOS"]},
    {"name": "EOS$ebnf$1", "symbols": ["EOS$ebnf$1", "S_EOS"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "EOS", "symbols": ["EOS$ebnf$1"], "postprocess": (d) => () => null},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$1", "symbols": [/[0-9,a-z,A-Z$_]/]},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$1", "symbols": ["S_IDENTIFIER$subexpression$1$ebnf$1", /[0-9,a-z,A-Z$_]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "S_IDENTIFIER$subexpression$1", "symbols": ["S_IDENTIFIER$subexpression$1$ebnf$1"], "postprocess": d => d[0].join('')},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$2", "symbols": [/[a-zA-Z0-9_$\x01-\x59\x61-\xff]/]},
    {"name": "S_IDENTIFIER$subexpression$1$ebnf$2", "symbols": ["S_IDENTIFIER$subexpression$1$ebnf$2", /[a-zA-Z0-9_$\x01-\x59\x61-\xff]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "S_IDENTIFIER$subexpression$1", "symbols": [{"literal":"`"}, "S_IDENTIFIER$subexpression$1$ebnf$2", {"literal":"`"}], "postprocess": d => d[1].join('')},
    {"name": "S_IDENTIFIER", "symbols": ["S_IDENTIFIER$subexpression$1"], "postprocess": id},
    {"name": "S_NUMBER$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "S_NUMBER$ebnf$1", "symbols": ["S_NUMBER$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "S_NUMBER", "symbols": ["S_NUMBER$ebnf$1"], "postprocess": d => Number(d[0].join(''))},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_INTEGER_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_FIXED_POINT_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_FLOATING_POINT_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_BIT_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_DATETIME_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_YEAR_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_VARIABLE_STRING_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_FIXED_STRING_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_ENUM_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_SET_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_SPATIAL_DATATYPE"]},
    {"name": "O_DATATYPE$subexpression$1", "symbols": ["O_JSON_DATATYPE"]},
    {"name": "O_DATATYPE", "symbols": ["O_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_DATATYPE',
            def: d[0][0]
          }
        }},
    {"name": "T_INTEGER$subexpression$1$subexpression$1", "symbols": [/[iI]/, /[nN]/, /[tT]/, /[eE]/, /[gG]/, /[eE]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_INTEGER$subexpression$1", "symbols": ["T_INTEGER$subexpression$1$subexpression$1"]},
    {"name": "T_INTEGER$subexpression$1$subexpression$2", "symbols": [/[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_INTEGER$subexpression$1", "symbols": ["T_INTEGER$subexpression$1$subexpression$2"]},
    {"name": "T_INTEGER", "symbols": ["T_INTEGER$subexpression$1"], "postprocess": d => { return d[0][0] }},
    {"name": "T_SMALLINT$subexpression$1", "symbols": [/[sS]/, /[mM]/, /[aA]/, /[lL]/, /[lL]/, /[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_SMALLINT", "symbols": ["T_SMALLINT$subexpression$1"], "postprocess": id},
    {"name": "T_TINYINT$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[nN]/, /[yY]/, /[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TINYINT", "symbols": ["T_TINYINT$subexpression$1"], "postprocess": id},
    {"name": "T_MEDIUMINT$subexpression$1", "symbols": [/[mM]/, /[eE]/, /[dD]/, /[iI]/, /[uU]/, /[mM]/, /[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_MEDIUMINT", "symbols": ["T_MEDIUMINT$subexpression$1"], "postprocess": id},
    {"name": "T_BIGINT$subexpression$1", "symbols": [/[bB]/, /[iI]/, /[gG]/, /[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_BIGINT", "symbols": ["T_BIGINT$subexpression$1"], "postprocess": id},
    {"name": "O_INTEGER_DATATYPE$subexpression$1", "symbols": ["T_INTEGER"]},
    {"name": "O_INTEGER_DATATYPE$subexpression$1", "symbols": ["T_SMALLINT"]},
    {"name": "O_INTEGER_DATATYPE$subexpression$1", "symbols": ["T_TINYINT"]},
    {"name": "O_INTEGER_DATATYPE$subexpression$1", "symbols": ["T_MEDIUMINT"]},
    {"name": "O_INTEGER_DATATYPE$subexpression$1", "symbols": ["T_BIGINT"]},
    {"name": "O_INTEGER_DATATYPE", "symbols": ["O_INTEGER_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_INTEGER_DATATYPE',
            def: d[0][0]
          }
        }},
    {"name": "T_DECIMAL$string$1", "symbols": [{"literal":"D"}, {"literal":"E"}, {"literal":"C"}, {"literal":"I"}, {"literal":"M"}, {"literal":"A"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "T_DECIMAL", "symbols": ["T_DECIMAL$string$1"], "postprocess": id},
    {"name": "T_NUMERIC$string$1", "symbols": [{"literal":"N"}, {"literal":"U"}, {"literal":"M"}, {"literal":"E"}, {"literal":"R"}, {"literal":"I"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "T_NUMERIC", "symbols": ["T_NUMERIC$string$1"], "postprocess": id},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1$subexpression$1", "symbols": ["T_DECIMAL"], "postprocess": id},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1$subexpression$1", "symbols": ["T_NUMERIC"], "postprocess": id},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":","}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess":  d => {
          return {
            digits: d[3] + d[7],
            decimals: d[7]
          }
        }},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess":  d => {
          return {
            digits: d[3],
            decimals: 0
          }
        }},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1$ebnf$1", "symbols": ["O_FIXED_POINT_DATATYPE$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "O_FIXED_POINT_DATATYPE$subexpression$1", "symbols": ["O_FIXED_POINT_DATATYPE$subexpression$1$subexpression$1", "O_FIXED_POINT_DATATYPE$subexpression$1$ebnf$1"]},
    {"name": "O_FIXED_POINT_DATATYPE", "symbols": ["O_FIXED_POINT_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_FIXED_POINT_DATATYPE',
            def: {
              datatype: d[0][0],
              spec: d[0][1]
            }
          }
        }},
    {"name": "T_FLOAT$string$1", "symbols": [{"literal":"F"}, {"literal":"L"}, {"literal":"O"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "T_FLOAT", "symbols": ["T_FLOAT$string$1"], "postprocess": id},
    {"name": "T_DOUBLE$string$1", "symbols": [{"literal":"D"}, {"literal":"O"}, {"literal":"U"}, {"literal":"B"}, {"literal":"L"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "T_DOUBLE", "symbols": ["T_DOUBLE$string$1"], "postprocess": id},
    {"name": "O_FLOATING_POINT_DATATYPE$subexpression$1$subexpression$1", "symbols": ["T_FLOAT"], "postprocess": id},
    {"name": "O_FLOATING_POINT_DATATYPE$subexpression$1$subexpression$1", "symbols": ["T_DOUBLE"], "postprocess": id},
    {"name": "O_FLOATING_POINT_DATATYPE$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":","}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess":  d => {
          return {
            digits: d[3] + d[7],
            decimals: d[7]
          }
        }},
    {"name": "O_FLOATING_POINT_DATATYPE$subexpression$1$ebnf$1", "symbols": ["O_FLOATING_POINT_DATATYPE$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "O_FLOATING_POINT_DATATYPE$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "O_FLOATING_POINT_DATATYPE$subexpression$1", "symbols": ["O_FLOATING_POINT_DATATYPE$subexpression$1$subexpression$1", "O_FLOATING_POINT_DATATYPE$subexpression$1$ebnf$1"]},
    {"name": "O_FLOATING_POINT_DATATYPE", "symbols": ["O_FLOATING_POINT_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_FLOATING_POINT_DATATYPE',
            def: {
              datatype: d[0][0],
              spec: d[0][1]
            }
          }
        }},
    {"name": "T_BIT$subexpression$1", "symbols": [/[bB]/, /[iI]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_BIT", "symbols": ["T_BIT$subexpression$1"], "postprocess": id},
    {"name": "O_BIT_DATATYPE", "symbols": ["T_BIT", "_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess":  d => {
          return {
            type: 'O_BIT_DATATYPE',
            def: {
              values: d[4]
            }
          }
        }},
    {"name": "T_DATE$subexpression$1", "symbols": [/[dD]/, /[aA]/, /[tT]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DATE", "symbols": ["T_DATE$subexpression$1"], "postprocess": id},
    {"name": "T_TIME$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[mM]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TIME", "symbols": ["T_TIME$subexpression$1"], "postprocess": id},
    {"name": "T_DATETIME$subexpression$1", "symbols": [/[dD]/, /[aA]/, /[tT]/, /[eE]/, /[tT]/, /[iI]/, /[mM]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_DATETIME", "symbols": ["T_DATETIME$subexpression$1"], "postprocess": id},
    {"name": "T_TIMESTAMP$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[mM]/, /[eE]/, /[sS]/, /[tT]/, /[aA]/, /[mM]/, /[pP]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TIMESTAMP", "symbols": ["T_TIMESTAMP$subexpression$1"], "postprocess": id},
    {"name": "O_DATETIME_DATATYPE$subexpression$1", "symbols": ["T_DATE"], "postprocess": id},
    {"name": "O_DATETIME_DATATYPE$subexpression$1", "symbols": ["T_TIME"], "postprocess": id},
    {"name": "O_DATETIME_DATATYPE$subexpression$1", "symbols": ["T_DATETIME"], "postprocess": id},
    {"name": "O_DATETIME_DATATYPE$subexpression$1", "symbols": ["T_TIMESTAMP"], "postprocess": id},
    {"name": "O_DATETIME_DATATYPE$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess": d => d[3]},
    {"name": "O_DATETIME_DATATYPE$ebnf$1", "symbols": ["O_DATETIME_DATATYPE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "O_DATETIME_DATATYPE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "O_DATETIME_DATATYPE", "symbols": ["O_DATETIME_DATATYPE$subexpression$1", "O_DATETIME_DATATYPE$ebnf$1"], "postprocess":  d => {
          return {
            type: 'O_DATETIME_DATATYPE',
            def: {
              datatype: d[0],
              fractional: d[1]
            }
          }
        }},
    {"name": "T_YEAR$subexpression$1", "symbols": [/[yY]/, /[eE]/, /[aA]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_YEAR", "symbols": ["T_YEAR$subexpression$1"], "postprocess": id},
    {"name": "O_YEAR_DATATYPE$ebnf$1$subexpression$1", "symbols": ["_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess": d => d[3]},
    {"name": "O_YEAR_DATATYPE$ebnf$1", "symbols": ["O_YEAR_DATATYPE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "O_YEAR_DATATYPE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "O_YEAR_DATATYPE", "symbols": ["_", "T_YEAR", "O_YEAR_DATATYPE$ebnf$1", "_"], "postprocess":  d => {
          return {
            type: 'O_YEAR_DATATYPE',
            def: {
              datatype: d[1],
              digits: d[2] || 4
            }
          }
        }},
    {"name": "T_CHAR$subexpression$1", "symbols": [/[cC]/, /[hH]/, /[aA]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_CHAR", "symbols": ["T_CHAR$subexpression$1"], "postprocess": id},
    {"name": "T_VARCHAR$subexpression$1", "symbols": [/[vV]/, /[aA]/, /[rR]/, /[cC]/, /[hH]/, /[aA]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_VARCHAR", "symbols": ["T_VARCHAR$subexpression$1"], "postprocess": id},
    {"name": "T_BINARY$subexpression$1", "symbols": [/[bB]/, /[iI]/, /[nN]/, /[aA]/, /[rR]/, /[yY]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_BINARY", "symbols": ["T_BINARY$subexpression$1"], "postprocess": id},
    {"name": "T_VARBINARY$subexpression$1", "symbols": [/[vV]/, /[aA]/, /[rR]/, /[bB]/, /[iI]/, /[nN]/, /[aA]/, /[rR]/, /[yY]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_VARBINARY", "symbols": ["T_VARBINARY$subexpression$1"], "postprocess": id},
    {"name": "O_VARIABLE_STRING_DATATYPE$subexpression$1", "symbols": ["T_CHAR"], "postprocess": id},
    {"name": "O_VARIABLE_STRING_DATATYPE$subexpression$1", "symbols": ["T_VARCHAR"], "postprocess": id},
    {"name": "O_VARIABLE_STRING_DATATYPE$subexpression$1", "symbols": ["T_BINARY"], "postprocess": id},
    {"name": "O_VARIABLE_STRING_DATATYPE$subexpression$1", "symbols": ["T_VARBINARY"], "postprocess": id},
    {"name": "O_VARIABLE_STRING_DATATYPE", "symbols": ["O_VARIABLE_STRING_DATATYPE$subexpression$1", "_", {"literal":"("}, "_", "S_NUMBER", "_", {"literal":")"}], "postprocess":  d => {
          return {
            type: 'O_VARIABLE_STRING_DATATYPE',
            def: {
              datatype: d[0],
              length: d[4]
            }
          }
        }},
    {"name": "T_TINYBLOB$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[nN]/, /[yY]/, /[bB]/, /[lL]/, /[oO]/, /[bB]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TINYBLOB", "symbols": ["T_TINYBLOB$subexpression$1"], "postprocess": id},
    {"name": "T_BLOB$subexpression$1", "symbols": [/[bB]/, /[lL]/, /[oO]/, /[bB]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_BLOB", "symbols": ["T_BLOB$subexpression$1"], "postprocess": id},
    {"name": "T_MEDIUMBLOB$subexpression$1", "symbols": [/[mM]/, /[eE]/, /[dD]/, /[iI]/, /[uU]/, /[mM]/, /[bB]/, /[lL]/, /[oO]/, /[bB]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_MEDIUMBLOB", "symbols": ["T_MEDIUMBLOB$subexpression$1"], "postprocess": id},
    {"name": "T_LONGBLOB$subexpression$1", "symbols": [/[lL]/, /[oO]/, /[nN]/, /[gG]/, /[bB]/, /[lL]/, /[oO]/, /[bB]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_LONGBLOB", "symbols": ["T_LONGBLOB$subexpression$1"], "postprocess": id},
    {"name": "T_TINYTEXT$subexpression$1", "symbols": [/[tT]/, /[iI]/, /[nN]/, /[yY]/, /[tT]/, /[eE]/, /[xX]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TINYTEXT", "symbols": ["T_TINYTEXT$subexpression$1"], "postprocess": id},
    {"name": "T_TEXT$subexpression$1", "symbols": [/[tT]/, /[eE]/, /[xX]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_TEXT", "symbols": ["T_TEXT$subexpression$1"], "postprocess": id},
    {"name": "T_MEDIUMTEXT$subexpression$1", "symbols": [/[mM]/, /[eE]/, /[dD]/, /[iI]/, /[uU]/, /[mM]/, /[tT]/, /[eE]/, /[xX]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_MEDIUMTEXT", "symbols": ["T_MEDIUMTEXT$subexpression$1"], "postprocess": id},
    {"name": "T_LONGTEXT$subexpression$1", "symbols": [/[lL]/, /[oO]/, /[nN]/, /[gG]/, /[tT]/, /[eE]/, /[xX]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_LONGTEXT", "symbols": ["T_LONGTEXT$subexpression$1"], "postprocess": id},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_TINYBLOB"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_BLOB"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_MEDIUMBLOB"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_LONGBLOB"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_TINYTEXT"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_TEXT"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_MEDIUMTEXT"]},
    {"name": "O_FIXED_STRING_DATATYPE$subexpression$1", "symbols": ["T_LONGTEXT"]},
    {"name": "O_FIXED_STRING_DATATYPE", "symbols": ["O_FIXED_STRING_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_FIXED_STRING_DATATYPE',
            def: {
              datatype: d[0][0],
            }
          }
        }},
    {"name": "T_ENUM$subexpression$1", "symbols": [/[eE]/, /[nN]/, /[uU]/, /[mM]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_ENUM", "symbols": ["T_ENUM$subexpression$1"], "postprocess": id},
    {"name": "O_ENUM_DATATYPE$subexpression$1$ebnf$1", "symbols": []},
    {"name": "O_ENUM_DATATYPE$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", {"literal":"'"}, "S_IDENTIFIER", {"literal":"'"}, "_"], "postprocess": d => d[4]},
    {"name": "O_ENUM_DATATYPE$subexpression$1$ebnf$1", "symbols": ["O_ENUM_DATATYPE$subexpression$1$ebnf$1", "O_ENUM_DATATYPE$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "O_ENUM_DATATYPE$subexpression$1", "symbols": ["_", {"literal":"("}, "_", {"literal":"'"}, "S_IDENTIFIER", {"literal":"'"}, "O_ENUM_DATATYPE$subexpression$1$ebnf$1", "_", {"literal":")"}], "postprocess": d => [d[4]].concat(d[6])},
    {"name": "O_ENUM_DATATYPE", "symbols": ["T_ENUM", "O_ENUM_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_ENUM_DATATYPE',
            def: {
              datatype: d[0],
              values: d[1],
            }
          }
        }},
    {"name": "T_SET$subexpression$1", "symbols": [/[sS]/, /[eE]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_SET", "symbols": ["T_SET$subexpression$1"], "postprocess": id},
    {"name": "O_SET_DATATYPE$subexpression$1", "symbols": [{"literal":"("}, "_", {"literal":"'"}, "S_IDENTIFIER", {"literal":"'"}, "_", {"literal":")"}], "postprocess": d => [d[3]]},
    {"name": "O_SET_DATATYPE$subexpression$1$ebnf$1", "symbols": []},
    {"name": "O_SET_DATATYPE$subexpression$1$ebnf$1$subexpression$1", "symbols": ["_", {"literal":","}, "_", {"literal":"'"}, "S_IDENTIFIER", {"literal":"'"}, "_"], "postprocess": d => d[4]},
    {"name": "O_SET_DATATYPE$subexpression$1$ebnf$1", "symbols": ["O_SET_DATATYPE$subexpression$1$ebnf$1", "O_SET_DATATYPE$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "O_SET_DATATYPE$subexpression$1", "symbols": [{"literal":"("}, "_", {"literal":"'"}, "S_IDENTIFIER", {"literal":"'"}, "O_SET_DATATYPE$subexpression$1$ebnf$1", "_", {"literal":")"}], "postprocess": d => Array.isArray(d[5]) ? [d[3]].concat(d[5]) : [d[3]]},
    {"name": "O_SET_DATATYPE", "symbols": ["T_SET", "_", "O_SET_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_SET_DATATYPE',
            def: {
              datatype: d[0],
              values: d[2],
            }
          }
        }},
    {"name": "T_GEOMETRY$subexpression$1", "symbols": [/[gG]/, /[eE]/, /[oO]/, /[mM]/, /[eE]/, /[tT]/, /[rR]/, /[yY]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_GEOMETRY", "symbols": ["T_GEOMETRY$subexpression$1"], "postprocess": id},
    {"name": "T_POINT$subexpression$1", "symbols": [/[pP]/, /[oO]/, /[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_POINT", "symbols": ["T_POINT$subexpression$1"], "postprocess": id},
    {"name": "T_LINESTRING$subexpression$1", "symbols": [/[lL]/, /[iI]/, /[nN]/, /[eE]/, /[sS]/, /[tT]/, /[rR]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_LINESTRING", "symbols": ["T_LINESTRING$subexpression$1"], "postprocess": id},
    {"name": "T_POLYGON$subexpression$1", "symbols": [/[pP]/, /[oO]/, /[lL]/, /[yY]/, /[gG]/, /[oO]/, /[nN]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_POLYGON", "symbols": ["T_POLYGON$subexpression$1"], "postprocess": id},
    {"name": "T_MULTIPOINT$subexpression$1", "symbols": [/[mM]/, /[uU]/, /[lL]/, /[tT]/, /[iI]/, /[pP]/, /[oO]/, /[iI]/, /[nN]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_MULTIPOINT", "symbols": ["T_MULTIPOINT$subexpression$1"], "postprocess": id},
    {"name": "T_MULTILINESTRING$subexpression$1", "symbols": [/[mM]/, /[uU]/, /[lL]/, /[tT]/, /[iI]/, /[lL]/, /[iI]/, /[nN]/, /[eE]/, /[sS]/, /[tT]/, /[rR]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_MULTILINESTRING", "symbols": ["T_MULTILINESTRING$subexpression$1"], "postprocess": id},
    {"name": "T_MULTIPOLYGON$subexpression$1", "symbols": [/[mM]/, /[uU]/, /[lL]/, /[tT]/, /[iI]/, /[pP]/, /[oO]/, /[lL]/, /[yY]/, /[gG]/, /[oO]/, /[nN]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_MULTIPOLYGON", "symbols": ["T_MULTIPOLYGON$subexpression$1"], "postprocess": id},
    {"name": "T_GEOMETRYCOLLECTION$subexpression$1", "symbols": [/[gG]/, /[eE]/, /[oO]/, /[mM]/, /[eE]/, /[tT]/, /[rR]/, /[yY]/, /[cC]/, /[oO]/, /[lL]/, /[lL]/, /[eE]/, /[cC]/, /[tT]/, /[iI]/, /[oO]/, /[nN]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_GEOMETRYCOLLECTION", "symbols": ["T_GEOMETRYCOLLECTION$subexpression$1"], "postprocess": id},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_GEOMETRY"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_POINT"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_LINESTRING"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_POLYGON"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_MULTIPOINT"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_MULTILINESTRING"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_MULTIPOLYGON"]},
    {"name": "O_SPATIAL_DATATYPE$subexpression$1", "symbols": ["T_GEOMETRYCOLLECTION"]},
    {"name": "O_SPATIAL_DATATYPE", "symbols": ["O_SPATIAL_DATATYPE$subexpression$1"], "postprocess":  d => {
          return {
            type: 'O_SPATIAL_DATATYPE',
            def: {
              datatype: d[0][0],
            }
          }
        }},
    {"name": "T_JSON$subexpression$1", "symbols": [/[jJ]/, /[sS]/, /[oO]/, /[nN]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "T_JSON", "symbols": ["T_JSON$subexpression$1"], "postprocess": id},
    {"name": "O_JSON_DATATYPE", "symbols": ["T_JSON"], "postprocess":  d => {
          return {
            type: 'O_JSON_DATATYPE',
            def: {
              datatype: d[0],
            }
          }
        }},
    {"name": "main", "symbols": ["O_DATATYPE"]},
    {"name": "P_DDS$subexpression$1", "symbols": ["P_CREATE_DB"], "postprocess": id},
    {"name": "P_DDS$subexpression$1", "symbols": ["P_CREATE_TABLE"], "postprocess": id},
    {"name": "P_DDS", "symbols": ["P_DDS$subexpression$1"], "postprocess":  d => {
          return {
            type: 'P_DDS',
            def: d[0]
          }
        }},
    {"name": "P_CREATE_DB$ebnf$1$subexpression$1", "symbols": ["__", "O_IFEXISTS"]},
    {"name": "P_CREATE_DB$ebnf$1", "symbols": ["P_CREATE_DB$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB$ebnf$2$subexpression$1", "symbols": ["__", "P_CREATE_DB_SPEC"]},
    {"name": "P_CREATE_DB$ebnf$2", "symbols": ["P_CREATE_DB$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB$ebnf$3", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_DB$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB", "symbols": ["_", "T_CREATE", "__", "T_DATABASE", "P_CREATE_DB$ebnf$1", "__", "S_IDENTIFIER", "P_CREATE_DB$ebnf$2", "P_CREATE_DB$ebnf$3"], "postprocess":  d => {
          return {
            type: 'P_CREATE_DB',
            def: {
              database: d[6]
            }
          }
        }},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$1$subexpression$1", "symbols": ["T_DEFAULT", "__"]},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$1", "symbols": ["P_CREATE_DB_SPEC$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$string$1", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"A"}, {"literal":"R"}, {"literal":"A"}, {"literal":"C"}, {"literal":"T"}, {"literal":"E"}, {"literal":"R"}, {"literal":" "}, {"literal":"S"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$2", "symbols": [{"literal":"="}], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1", "symbols": ["_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$1", "P_CREATE_DB_SPEC$subexpression$1$string$1", "_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$2", "_", "O_CHARSET_NAME", "_"], "postprocess": d => null},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$3$subexpression$1", "symbols": ["T_DEFAULT", "__"]},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$3", "symbols": ["P_CREATE_DB_SPEC$subexpression$1$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$string$2", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"L"}, {"literal":"L"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$4", "symbols": [{"literal":"="}], "postprocess": id},
    {"name": "P_CREATE_DB_SPEC$subexpression$1$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_DB_SPEC$subexpression$1", "symbols": ["_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$3", "P_CREATE_DB_SPEC$subexpression$1$string$2", "_", "P_CREATE_DB_SPEC$subexpression$1$ebnf$4", "_", "O_COLLATION_NAME", "_"], "postprocess": d => null},
    {"name": "P_CREATE_DB_SPEC", "symbols": ["P_CREATE_DB_SPEC$subexpression$1"], "postprocess": d => null},
    {"name": "P_CREATE_TABLE$ebnf$1$subexpression$1", "symbols": ["__", "T_TEMPORARY"]},
    {"name": "P_CREATE_TABLE$ebnf$1", "symbols": ["P_CREATE_TABLE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_TABLE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE$ebnf$2$subexpression$1", "symbols": ["__", "O_IFEXISTS"]},
    {"name": "P_CREATE_TABLE$ebnf$2", "symbols": ["P_CREATE_TABLE$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_TABLE$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE$ebnf$3", "symbols": []},
    {"name": "P_CREATE_TABLE$ebnf$3", "symbols": ["P_CREATE_TABLE$ebnf$3", "P_CREATE_TABLE_SPEC"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "P_CREATE_TABLE$ebnf$4$subexpression$1", "symbols": ["__", "P_CREATE_TABLE_OPTIONS"]},
    {"name": "P_CREATE_TABLE$ebnf$4", "symbols": ["P_CREATE_TABLE$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_TABLE$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE$ebnf$5$subexpression$1", "symbols": ["__", "P_CREATE_TABLE_PART_OPTIONS"]},
    {"name": "P_CREATE_TABLE$ebnf$5", "symbols": ["P_CREATE_TABLE$ebnf$5$subexpression$1"], "postprocess": id},
    {"name": "P_CREATE_TABLE$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE$ebnf$6", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_TABLE$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE", "symbols": ["_", "T_CREATE", "P_CREATE_TABLE$ebnf$1", "__", "T_TABLE", "P_CREATE_TABLE$ebnf$2", "__", "S_IDENTIFIER", "_", "P_CREATE_TABLE$ebnf$3", "P_CREATE_TABLE$ebnf$4", "P_CREATE_TABLE$ebnf$5", "P_CREATE_TABLE$ebnf$6"], "postprocess":  d => {
          return {
            type: 'P_CREATE_TABLE',
            def: {
              table: d[7],
              spec: d[9]
            }
          }
        }},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$1", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$2", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$3", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1", "symbols": ["S_IDENTIFIER", "__", "P_COLUMN_DEFINITION", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$1", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$2", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1$ebnf$3"]},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1", "symbols": ["P_CREATE_TABLE_SPEC$ebnf$1$subexpression$1"]},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$1", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$2", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$3", "symbols": ["EOS"], "postprocess": id},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2", "symbols": ["S_IDENTIFIER", "__", "P_COLUMN_DEFINITION", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$1", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$2", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2$ebnf$3"]},
    {"name": "P_CREATE_TABLE_SPEC$ebnf$1", "symbols": ["P_CREATE_TABLE_SPEC$ebnf$1", "P_CREATE_TABLE_SPEC$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "P_CREATE_TABLE_SPEC", "symbols": ["_", {"literal":"("}, "_", "P_CREATE_TABLE_SPEC$ebnf$1", "_", {"literal":")"}, "_"], "postprocess":  d => {
          return {
            type: 'P_CREATE_TABLE_SPEC',
            def: d[3]
          }
        }},
    {"name": "P_COLUMN_DEFINITION$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}, {"literal":"D"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_COLUMN_DEFINITION", "symbols": ["P_COLUMN_DEFINITION$string$1"]},
    {"name": "P_CREATE_TABLE_OPTIONS$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}, {"literal":"D"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_CREATE_TABLE_OPTIONS", "symbols": ["P_CREATE_TABLE_OPTIONS$string$1"]},
    {"name": "P_CREATE_TABLE_PART_OPTIONS$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}, {"literal":"D"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P_CREATE_TABLE_PART_OPTIONS", "symbols": ["P_CREATE_TABLE_PART_OPTIONS$string$1"]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
